name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
  
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore

    - name: Pack with dotnet
      run: dotnet pack PureManApplicationDevelopment --configuration Release

    - name: debug
      run: |
          cd ./PureManApplicationDevelopment/bin/Release
          ls

    - name: Push to Github Packages   
      run: dotnet nuget push ./PureManApplicationDevelopment/bin/Release/PureManApplicationDevelopment.*.nupkg  --source "https://nuget.pkg.github.com/blue-10/index.json" --api-key ${{ secrets.GITHUB_TOKEN }}
