name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
  
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore

    - name: Pack with dotnet
      run: dotnet pack PureManApplicationDevelopment --configuration Release

    - name: Push to Github Packages   
      run: dotnet nuget push ./PureManApplicationDevelopment/bin/Release/PureManApplicationDeployment.*.nupkg -s "https://nuget.pkg.github.com/blue-10/index.json" -k ${{ secrets.GITHUB_TOKEN }} --skip-duplicate

    - name: Push to Nuget
      run: dotnet nuget push ./PureManApplicationDevelopment/bin/Release/PureManApplicationDeployment.*.nupkg -s https://www.nuget.org/ -k ${{ secrets.NUGET_KEY }} --skip-duplicate